### ISSUE TITLE
Pressure advance tool

### ISSUE THREAD

**Issue by chrstrvs** [AndrewEllis93/Print-Tuning-Guide#51] opened 2022-12-21 17:46 UTC
In the Pressure Advance / Linear Advance Calibration Tool the End G-code doesn't work as intended. When changing to something else than the preset it doesn't take. The generated gcode still contains the preset gcode, which is "PRINT_END ; End macro. Change name to match yours".

**Comment by AndrewEllis93** [comment] 2022-12-21 22:14
Closing as duplicate of:
https://github.com/AndrewEllis93/Pressure_Linear_Advance_Tool/issues/12

I will look into this

**Closed by AndrewEllis93** 2022-12-21 22:14 UTC
